### REGISTER Admin
POST http://localhost:5001/api/admin/register
Content-Type: application/json
Accept: application/json

{
  "username": "admin_baru",
  "password" : "Password123."
}

### LOGIN admin
POST http://localhost:5001/api/admin/login
Content-Type: application/json
Accept: application/json

{
  "username": "admin_baru",
  "password" : "Password123."
}

// Simpan token yang didapat dari respons login ini ke variabel lingkungan {{token_admin}}
// Contoh: "token": "YOUR_ADMIN_TOKEN_HERE"


### GET Admin Profile (Current)
GET http://localhost:5001/api/admin/current
Authorization: Bearer {{token_admin}}
Accept: application/json


### UPDATE Admin Profile
PATCH http://localhost:5001/api/admin/current
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token_admin}}

{
  "username": "admin_heru_updated"
}


### UPDATE Admin Password
PATCH http://localhost:5001/api/admin/current/password
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token_admin}}

{
  "oldPassword": "Password123.",
  "newPassword": "NewPassword123."
}


### DELETE Admin Account
DELETE http://localhost:5001/api/admin/current
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token_admin}}

{
  "password": "NewPassword123." // Gunakan password admin saat ini
}


### LOGOUT Admin
DELETE http://localhost:5001/api/admin/logout
Accept: application/json
Authorization: Bearer {{token_admin}}